Draft 027
authwit/newsletter-briefsweekly pull request #21
Opened 2021-08-25 08:43 UTC by ESTHER0533

@deletosh add draft 027

2021-09-01 19:26 UTC, deletosh requested changes
@ESTHER0533 please see my review and update according

2021-09-01 19:26 UTC, deletosh commented on 027.md
> +## Brief #027:What the heck is LegalTech – An introduction to and overview of the technology disrupting the legal profession
@ESTHER0533 can you please update this to follow the proper title syntax (adding the content of this, with the, "and more"

2021-09-01 19:26 UTC, deletosh commented on 027.md
> +Legal Technology is not a new concept though as technology has played an important part in the jobs of lawyers both in-house and at law firms. Two aspects though have created a movement that aims to
@ESTHER0533 this block seems incomplete, can you comfirm. I don't see the point of ending in a ":"

2021-09-05 20:06 UTC, ESTHER0533 commented on 027.md
> +## Brief #027:What the heck is LegalTech – An introduction to and overview of the technology disrupting the legal profession
@deletosh i dont really understand your inference on this

2021-09-06 07:17 UTC, deletosh commented on 027.md
> +## Brief #027:What the heck is LegalTech – An introduction to and overview of the technology disrupting the legal profession
@ESTHER0533 this is the title of the newsletter. It should have something like "Brief #027: What the heck is LegalTech, Abridged Title from Another Article, Maybe One More, and more."

2021-09-06 08:17 UTC, ESTHER0533 commented on 027.md
> +## Brief #027:What the heck is LegalTech – An introduction to and overview of the technology disrupting the legal profession
@deletosh Do you mean other sum titles, they are indicated in this article Sir,
![image](https://user-images.githubusercontent.com/83968328/132183875-05241358-d19c-453c-bc99-d2185aba2cbd.png)

2021-09-07 08:07 UTC, ESTHER0533 commented
@deletosh Draft 027 updated

2021-09-07 11:54 UTC, deletosh commented on 027.md
> +## Brief #027:What the heck is LegalTech – An introduction to and overview of the technology disrupting the legal profession
@ESTHER0533 this section

![](https://static.authw.it/Draft_027_by_ESTHER0533__Pull_Request_21__authwitnewsletter-briefsweekly_2021-09-07_07-53-32.png)

Is what should have the updated subject line

2021-09-08 09:38 UTC, ESTHER0533 commented on 027.md
> +## Brief #027:What the heck is LegalTech – An introduction to and overview of the technology disrupting the legal profession
@deletosh Do you me the heading should also be among the Sub headings i.e , the extracts?

2021-09-08 18:16 UTC, deletosh commented on 027.md
> +## Brief #027:What the heck is LegalTech – An introduction to and overview of the technology disrupting the legal profession
@ESTHER0533 yes.

2021-09-09 15:42 UTC, ESTHER0533 commented on 027.md
> +## Brief #027:What the heck is LegalTech – An introduction to and overview of the technology disrupting the legal profession
@deletosh Sir, I cant seem to find this markdown file anymore, did you delete?

2021-09-09 21:30 UTC, ESTHER0533 reviewed
@deletosh  changes made

2021-09-19 21:42 UTC, merged